---
driver_plugin: vagrant
platforms:
- name: centos-6.3
  driver_config:
    box: centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
    customize:
      memory: 2048
      cpus: 4
suites:
- name: default
  run_list:
    - recipe[up2date]
    - recipe[qmailtoaster]
    - recipe[minitest-handler]
  attributes:
    qmailtoaster:
      vpopmail:
        database:
          password: vpopmail
    mysql:
      server_root_password: root
      server_repl_password: repl
      server_debian_password: debian
